@RD /S /Q "C:\Users\07cal\Documents\Python\acs\IES\Definitive\7-8\Apartats 7 i 8 by Albert CS.exe"
@RD /S /Q "C:\Users\07cal\Documents\Python\acs\IES\Definitive\7-8\Apartats 7 i 8 by Albert CS.spec"
move "C:\Users\07cal\Documents\Python\acs\IES\Definitive\7-8\dist\Apartats 7 i 8 by Albert CS.exe" "C:\Users\07cal\Documents\Python\acs\IES\Definitive\7-8"
@RD /S /Q "C:\Users\07cal\Documents\Python\acs\IES\Definitive\7-8\build"
@RD /S /Q "C:\Users\07cal\Documents\Python\acs\IES\Definitive\7-8\dist"
@RD /S /Q "C:\Users\07cal\Documents\Python\acs\IES\Definitive\7-8\__pycache__"